IMPORT_FILE = 'IMPORT_FILE'
WORKING_DIR = 'WORKING_DIR'
log_importing = '--- # Importing data data from {}'
log_total_rows = '--- ### Total rows on {} data : {} rows'
log_top_contributors = '--- ### Top {} contributors on {} data :'
log_q_by_claim = '--- ### Kualifikasi #MendataVtuberID [Mengakui diri dan diakui oleh khalayak sebagai Virtual ' \
                 'Youtuber Indie Indonesia]'
log_q_by_original_character = '--- ### Kualifikasi #MendataVtuberID [Memiliki dan menggunakan original character]'
log_q_by_already_debut = '--- ### Kualifikasi #MendataVtuberID [Merupakan Virtual Youtuber independen yang telah debut]'
log_q_by_content = '--- ### Kualifikasi #MendataVtuberID [Akun Youtube didominasi oleh konten Virtual Youtuber]'
log_q_by_active_on_past_3_months = '--- ### Kualifikasi #MendataVtuberID [Akun Virtual Youtuber dengan keaktifan ' \
                                   'maksimal 3 bulan terakhir]'
log_q_by_public_subs_count = '--- ### Kualifikasi #MendataVtuberID [Jumlah subscriber Youtube terlihat secara publik]'
NO = 'Tidak'
YES = 'Ya'
